import * as THREE from 'three';import{OrbitControls}from'three/addons/controls/OrbitControls.js';import{GLTFLoader}from'three/addons/loaders/GLTFLoader.js';import{groups,models}from'./config.js';
const state=Object.fromEntries(groups.map(g=>[g.id,new URLSearchParams(location.search).get(g.id)||g.default]));
const controls=document.querySelector('#controls'),summary=document.querySelector('#summary');
for(const g of groups){const d=document.createElement('div');d.className='group';d.innerHTML=`<h3>${g.label}</h3>`;for(const o of g.options){const l=document.createElement('label');l.className='option';l.innerHTML=`<input type="radio" name="${g.id}" value="${o.id}" ${state[g.id]===o.id?'checked':''}>${o.label}`;l.querySelector('input').onchange=()=>{state[g.id]=o.id;update()};d.append(l)}controls.append(d)}
const canvas=document.querySelector('#viewer'),renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(35,1,.1,2000);camera.position.set(180,120,220);const orbit=new OrbitControls(camera,canvas);orbit.enableDamping=true;scene.add(new THREE.HemisphereLight(0xffffff,0x333333,2.2));const dl=new THREE.DirectionalLight(0xffffff,3);dl.position.set(100,160,120);scene.add(dl);const root=new THREE.Group();scene.add(root);const loaded=new Map(),loader=new GLTFLoader();
async function loadModel(id){if(loaded.has(id))return loaded.get(id);try{const gltf=await loader.loadAsync(models[id].file);loaded.set(id,gltf.scene);root.add(gltf.scene);return gltf.scene}catch(e){return null}}
function selectedModelIds(){const s=new Set();for(const g of groups){const o=g.options.find(x=>x.id===state[g.id]);o?.models.forEach(x=>s.add(x))}return s}
async function update(){const wanted=selectedModelIds();for(const id of wanted)await loadModel(id);for(const[id,obj]of loaded)obj.visible=wanted.has(id);summary.innerHTML=groups.map(g=>`<span class="pill">${g.options.find(o=>o.id===state[g.id])?.label}</span>`).join('');const q=new URLSearchParams(state);history.replaceState(null,'','?'+q);document.querySelector('#notice').style.display=loaded.size?'none':'block'}
function resize(){const w=canvas.clientWidth,h=canvas.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}function animate(){resize();orbit.update();renderer.render(scene,camera);requestAnimationFrame(animate)}animate();update();
document.querySelector('#share').onclick=async()=>{await navigator.clipboard.writeText(location.href);alert('Configuration link copied')};document.querySelector('#reset').onclick=()=>{for(const g of groups)state[g.id]=g.default;location.search=new URLSearchParams(state)};document.querySelector('#fit').onclick=()=>{camera.position.set(180,120,220);orbit.target.set(0,0,0)};document.querySelector('#download').onclick=()=>alert('Download bundle will activate after the printable STL files are mapped.');let exploded=false;document.querySelector('#explode').onclick=()=>{exploded=!exploded;let i=0;for(const o of loaded.values())o.position.x=exploded?(i++-loaded.size/2)*35:0};
