import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {DRACOLoader} from 'three/addons/loaders/DRACOLoader.js';

const files = [
'A1 gear setup parts.glb','Back Electronics housing.glb','Body for H2D left heating assembly.glb','Body for h2d right heating assembly.glb','Electronics.glb','Filament Cutter harm.glb','Gantry for MGN9 RAILS.step.glb','H2S Extruder Gear system.glb','MGN12H  carriage.glb','Main Body for H2S Extruder gear.glb','Monolith carriage.glb','OZNLAB sensor setu H2S gear.step.glb','RX-H2S Gear toolhead 5015 V4.5.3.x_t.glb','carriage mount for BIQU microprobe.glb','carto mount.glb','connectors.glb','default connector.glb','extruder gear Box.glb','extruder gear box for Dual Filament sensor.glb','filament cutter depressor.glb','front cover.glb','longer back cover.glb','screws and fasteners.glb'];
const $=s=>document.querySelector(s); const sel=$('#assembly'); files.forEach(f=>sel.add(new Option(f.replace(/\.glb$/,''),f)));
function makeViewer(el){const scene=new THREE.Scene();scene.background=new THREE.Color(0x0d0f11);const camera=new THREE.PerspectiveCamera(40,1,.001,100);camera.position.set(.45,.3,.55);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;el.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x333333,2.2));const dl=new THREE.DirectionalLight(0xffffff,2.2);dl.position.set(1,2,3);scene.add(dl);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;function resize(){const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}function loop(){resize();controls.update();renderer.render(scene,camera);requestAnimationFrame(loop)}loop();return{scene,camera,controls,renderer}}
const mv=makeViewer($('#master')), rv=makeViewer($('#reference'));
const draco=new DRACOLoader();draco.setDecoderPath('https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/libs/draco/');const loader=new GLTFLoader();loader.setDRACOLoader(draco);
const load=url=>new Promise((res,rej)=>loader.load(url,res,undefined,rej));
function fit(v,obj){const b=new THREE.Box3().setFromObject(obj),s=b.getSize(new THREE.Vector3()),c=b.getCenter(new THREE.Vector3()),m=Math.max(s.x,s.y,s.z)||1;v.controls.target.copy(c);v.camera.position.copy(c).add(new THREE.Vector3(m*1.5,m*.9,m*1.7));v.camera.near=m/1000;v.camera.far=m*100;v.camera.updateProjectionMatrix();v.controls.update()}
function colorOf(mesh){let m=Array.isArray(mesh.material)?mesh.material[0]:mesh.material;let c=m?.color||new THREE.Color(1,1,1);return[c.r,c.g,c.b]}
function descriptor(mesh,id){mesh.updateWorldMatrix(true,false);const b=new THREE.Box3().setFromObject(mesh),d=b.getSize(new THREE.Vector3());const dims=[d.x,d.y,d.z].sort((a,b)=>a-b);const pos=mesh.geometry.attributes.position?.count||0;const tri=(mesh.geometry.index?.count||pos)/3;return{id,mesh,dims,tri,color:colorOf(mesh)}}
function score(a,b){let ds=0;for(let i=0;i<3;i++){const x=Math.max(a.dims[i],1e-6),y=Math.max(b.dims[i],1e-6);ds+=Math.abs(Math.log(x/y))}ds/=3;const ts=Math.abs(Math.log((a.tri+20)/(b.tri+20)));const cs=Math.sqrt(a.color.reduce((q,x,i)=>q+(x-b.color[i])**2,0))/1.732;return ds*5+ts*.55+cs*1.4}
function confidence(s){return s<.12?'HIGH':s<.28?'GOOD':s<.55?'CHECK':'LOW'}
let masterRoot, master=[], refRoot, refs=[], selected=0,candIndex=0,candidates=[],mapping=JSON.parse(localStorage.getItem('rxMappingV4')||'{}');
const originalMat=new Map();function clearHighlight(){master.forEach(x=>{if(originalMat.has(x.mesh)){x.mesh.material=originalMat.get(x.mesh);originalMat.delete(x.mesh)}})}function highlight(id){clearHighlight();const x=master.find(x=>x.id===id);if(!x)return;originalMat.set(x.mesh,x.mesh.material);const m=new THREE.MeshStandardMaterial({color:0xffdf22,emissive:0x6b5600,metalness:0,roughness:.35});x.mesh.material=m}
function computeCandidates(){if(!refs.length)return;candidates=master.map(m=>({id:m.id,s:score(refs[selected],m)})).sort((a,b)=>a.s-b.s);candIndex=0;const saved=mapping[sel.value]?.find(x=>x.ref===selected);if(saved){const k=candidates.findIndex(x=>x.id===saved.master);if(k>=0)candIndex=k}highlight(candidates[candIndex].id);renderParts();updateStatus()}
function renderParts(){const box=$('#parts');box.innerHTML='';refs.forEach((r,i)=>{const c=master.map(m=>({id:m.id,s:score(r,m)})).sort((a,b)=>a.s-b.s)[0];const saved=mapping[sel.value]?.find(x=>x.ref===i);const div=document.createElement('div');div.className='part '+(i===selected?'active ':'')+(saved?'confirmed':'');div.innerHTML=`<b>Body ${i+1}</b><small>${saved?`✓ Master #${saved.master}`:`best #${c.id} · ${confidence(c.s)} · score ${c.s.toFixed(3)}`}</small>`;div.onclick=()=>{selected=i;computeCandidates()};box.appendChild(div)})}
function updateStatus(){if(!refs.length||!candidates.length)return;const c=candidates[candIndex];$('#status').textContent=`Reference body ${selected+1} → candidate Master #${c.id} · ${confidence(c.s)} · score ${c.s.toFixed(3)} · candidate ${candIndex+1}/${candidates.length}`}
async function loadRef(){if(refRoot)rv.scene.remove(refRoot);$('#refname').textContent=sel.value;$('#status').textContent='Loading named reference…';const g=await load('./assets/reference/'+encodeURIComponent(sel.value));refRoot=g.scene;rv.scene.add(refRoot);refs=[];refRoot.traverse(o=>{if(o.isMesh)refs.push(descriptor(o,refs.length))});fit(rv,refRoot);selected=0;$('#stats').textContent=`Master: ${master.length} meshes · Reference: ${refs.length} bodies`;computeCandidates()}
sel.onchange=loadRef;$('#prev').onclick=()=>{candIndex=(candIndex-1+candidates.length)%candidates.length;highlight(candidates[candIndex].id);updateStatus()};$('#next').onclick=()=>{candIndex=(candIndex+1)%candidates.length;highlight(candidates[candIndex].id);updateStatus()};
$('#confirm').onclick=()=>{const key=sel.value;mapping[key]=(mapping[key]||[]).filter(x=>x.ref!==selected);mapping[key].push({ref:selected,master:candidates[candIndex].id,score:+candidates[candIndex].s.toFixed(5),confidence:confidence(candidates[candIndex].s)});localStorage.setItem('rxMappingV4',JSON.stringify(mapping));renderParts()};
$('#auto').onclick=()=>{const key=sel.value;let used=new Set((mapping[key]||[]).map(x=>x.master));let arr=(mapping[key]||[]).slice();refs.forEach((r,i)=>{if(arr.some(x=>x.ref===i))return;const cs=master.map(m=>({id:m.id,s:score(r,m)})).sort((a,b)=>a.s-b.s);const c=cs.find(x=>!used.has(x.id));if(c&&c.s<.12){arr.push({ref:i,master:c.id,score:+c.s.toFixed(5),confidence:'HIGH'});used.add(c.id)}});mapping[key]=arr;localStorage.setItem('rxMappingV4',JSON.stringify(mapping));renderParts();$('#status').textContent=`Confirmed ${arr.length}/${refs.length} bodies for ${key}.`};
$('#clear').onclick=()=>{delete mapping[sel.value];localStorage.setItem('rxMappingV4',JSON.stringify(mapping));renderParts()};$('#export').onclick=()=>{const blob=new Blob([JSON.stringify({version:4,knownValidation:{masterMesh39:'servo'},assemblies:mapping},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='rx-v55-mapping.json';a.click();URL.revokeObjectURL(a.href)};
const mg=await load('./assets/models/rx-v55-master.glb');masterRoot=mg.scene;mv.scene.add(masterRoot);master=[];masterRoot.traverse(o=>{if(o.isMesh)master.push(descriptor(o,master.length))});fit(mv,masterRoot);$('#status').textContent='Master loaded. Loading first named reference…';await loadRef();
